# Generated by Django 5.0.2 on 2024-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RescueContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "medical_qualifications",
                    models.CharField(
                        choices=[
                            ("Doctor", "Doctor"),
                            ("First aid", "First aid"),
                            ("Midwife", "Midwife"),
                            ("Nurse", "Nurse"),
                            ("Paramedic", "Paramedic"),
                            ("Qualified first aid", "Qualified first aid"),
                        ],
                        default="Qualified first aid",
                        help_text="Qualifications",
                        max_length=50,
                    ),
                ),
                ("is_driver", models.BooleanField(default=False)),
                ("has_vehicle_driving_privileges", models.BooleanField(default=False)),
                ("is_navigator", models.BooleanField(default=False)),
                ("is_planner", models.BooleanField(default=False)),
            ],
        ),
    ]
