# Generated by Django 5.0.2 on 2024-02-26 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rescuecontact_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rescuecontact",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
